/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedThreatsRouteImport } from './routes/_authenticated/threats'
import { Route as AuthenticatedSpamCallsRouteImport } from './routes/_authenticated/spam-calls'
import { Route as AuthenticatedScamMessagesRouteImport } from './routes/_authenticated/scam-messages'
import { Route as AuthenticatedPhishingUrlsRouteImport } from './routes/_authenticated/phishing-urls'
import { Route as AuthenticatedMaliciousIpsRouteImport } from './routes/_authenticated/malicious-ips'
import { Route as AuthenticatedEmailScamsRouteImport } from './routes/_authenticated/email-scams'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatbotRouteImport } from './routes/_authenticated/chatbot'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedThreatsRoute = AuthenticatedThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpamCallsRoute = AuthenticatedSpamCallsRouteImport.update({
  id: '/spam-calls',
  path: '/spam-calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScamMessagesRoute =
  AuthenticatedScamMessagesRouteImport.update({
    id: '/scam-messages',
    path: '/scam-messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPhishingUrlsRoute =
  AuthenticatedPhishingUrlsRouteImport.update({
    id: '/phishing-urls',
    path: '/phishing-urls',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaliciousIpsRoute =
  AuthenticatedMaliciousIpsRouteImport.update({
    id: '/malicious-ips',
    path: '/malicious-ips',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmailScamsRoute = AuthenticatedEmailScamsRouteImport.update({
  id: '/email-scams',
  path: '/email-scams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatbotRoute = AuthenticatedChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-scams': typeof AuthenticatedEmailScamsRoute
  '/malicious-ips': typeof AuthenticatedMaliciousIpsRoute
  '/phishing-urls': typeof AuthenticatedPhishingUrlsRoute
  '/scam-messages': typeof AuthenticatedScamMessagesRoute
  '/spam-calls': typeof AuthenticatedSpamCallsRoute
  '/threats': typeof AuthenticatedThreatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-scams': typeof AuthenticatedEmailScamsRoute
  '/malicious-ips': typeof AuthenticatedMaliciousIpsRoute
  '/phishing-urls': typeof AuthenticatedPhishingUrlsRoute
  '/scam-messages': typeof AuthenticatedScamMessagesRoute
  '/spam-calls': typeof AuthenticatedSpamCallsRoute
  '/threats': typeof AuthenticatedThreatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chatbot': typeof AuthenticatedChatbotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-scams': typeof AuthenticatedEmailScamsRoute
  '/_authenticated/malicious-ips': typeof AuthenticatedMaliciousIpsRoute
  '/_authenticated/phishing-urls': typeof AuthenticatedPhishingUrlsRoute
  '/_authenticated/scam-messages': typeof AuthenticatedScamMessagesRoute
  '/_authenticated/spam-calls': typeof AuthenticatedSpamCallsRoute
  '/_authenticated/threats': typeof AuthenticatedThreatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chatbot'
    | '/dashboard'
    | '/email-scams'
    | '/malicious-ips'
    | '/phishing-urls'
    | '/scam-messages'
    | '/spam-calls'
    | '/threats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chatbot'
    | '/dashboard'
    | '/email-scams'
    | '/malicious-ips'
    | '/phishing-urls'
    | '/scam-messages'
    | '/spam-calls'
    | '/threats'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chatbot'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-scams'
    | '/_authenticated/malicious-ips'
    | '/_authenticated/phishing-urls'
    | '/_authenticated/scam-messages'
    | '/_authenticated/spam-calls'
    | '/_authenticated/threats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/threats': {
      id: '/_authenticated/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof AuthenticatedThreatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spam-calls': {
      id: '/_authenticated/spam-calls'
      path: '/spam-calls'
      fullPath: '/spam-calls'
      preLoaderRoute: typeof AuthenticatedSpamCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scam-messages': {
      id: '/_authenticated/scam-messages'
      path: '/scam-messages'
      fullPath: '/scam-messages'
      preLoaderRoute: typeof AuthenticatedScamMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/phishing-urls': {
      id: '/_authenticated/phishing-urls'
      path: '/phishing-urls'
      fullPath: '/phishing-urls'
      preLoaderRoute: typeof AuthenticatedPhishingUrlsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/malicious-ips': {
      id: '/_authenticated/malicious-ips'
      path: '/malicious-ips'
      fullPath: '/malicious-ips'
      preLoaderRoute: typeof AuthenticatedMaliciousIpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-scams': {
      id: '/_authenticated/email-scams'
      path: '/email-scams'
      fullPath: '/email-scams'
      preLoaderRoute: typeof AuthenticatedEmailScamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbot': {
      id: '/_authenticated/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AuthenticatedChatbotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatbotRoute: typeof AuthenticatedChatbotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailScamsRoute: typeof AuthenticatedEmailScamsRoute
  AuthenticatedMaliciousIpsRoute: typeof AuthenticatedMaliciousIpsRoute
  AuthenticatedPhishingUrlsRoute: typeof AuthenticatedPhishingUrlsRoute
  AuthenticatedScamMessagesRoute: typeof AuthenticatedScamMessagesRoute
  AuthenticatedSpamCallsRoute: typeof AuthenticatedSpamCallsRoute
  AuthenticatedThreatsRoute: typeof AuthenticatedThreatsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatbotRoute: AuthenticatedChatbotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailScamsRoute: AuthenticatedEmailScamsRoute,
  AuthenticatedMaliciousIpsRoute: AuthenticatedMaliciousIpsRoute,
  AuthenticatedPhishingUrlsRoute: AuthenticatedPhishingUrlsRoute,
  AuthenticatedScamMessagesRoute: AuthenticatedScamMessagesRoute,
  AuthenticatedSpamCallsRoute: AuthenticatedSpamCallsRoute,
  AuthenticatedThreatsRoute: AuthenticatedThreatsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
