/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreatsRouteImport } from './routes/threats'
import { Route as SpamCallsRouteImport } from './routes/spam-calls'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScamMessagesRouteImport } from './routes/scam-messages'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PhishingUrlsRouteImport } from './routes/phishing-urls'
import { Route as MaliciousIpsRouteImport } from './routes/malicious-ips'
import { Route as EmailScamsRouteImport } from './routes/email-scams'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as CallSmsIntelRouteImport } from './routes/call-sms-intel'
import { Route as IndexRouteImport } from './routes/index'

const ThreatsRoute = ThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const SpamCallsRoute = SpamCallsRouteImport.update({
  id: '/spam-calls',
  path: '/spam-calls',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamMessagesRoute = ScamMessagesRouteImport.update({
  id: '/scam-messages',
  path: '/scam-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PhishingUrlsRoute = PhishingUrlsRouteImport.update({
  id: '/phishing-urls',
  path: '/phishing-urls',
  getParentRoute: () => rootRouteImport,
} as any)
const MaliciousIpsRoute = MaliciousIpsRouteImport.update({
  id: '/malicious-ips',
  path: '/malicious-ips',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailScamsRoute = EmailScamsRouteImport.update({
  id: '/email-scams',
  path: '/email-scams',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const CallSmsIntelRoute = CallSmsIntelRouteImport.update({
  id: '/call-sms-intel',
  path: '/call-sms-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/call-sms-intel': typeof CallSmsIntelRoute
  '/chatbot': typeof ChatbotRoute
  '/dashboard': typeof DashboardRoute
  '/email-scams': typeof EmailScamsRoute
  '/malicious-ips': typeof MaliciousIpsRoute
  '/phishing-urls': typeof PhishingUrlsRoute
  '/reports': typeof ReportsRoute
  '/scam-messages': typeof ScamMessagesRoute
  '/settings': typeof SettingsRoute
  '/spam-calls': typeof SpamCallsRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call-sms-intel': typeof CallSmsIntelRoute
  '/chatbot': typeof ChatbotRoute
  '/dashboard': typeof DashboardRoute
  '/email-scams': typeof EmailScamsRoute
  '/malicious-ips': typeof MaliciousIpsRoute
  '/phishing-urls': typeof PhishingUrlsRoute
  '/reports': typeof ReportsRoute
  '/scam-messages': typeof ScamMessagesRoute
  '/settings': typeof SettingsRoute
  '/spam-calls': typeof SpamCallsRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/call-sms-intel': typeof CallSmsIntelRoute
  '/chatbot': typeof ChatbotRoute
  '/dashboard': typeof DashboardRoute
  '/email-scams': typeof EmailScamsRoute
  '/malicious-ips': typeof MaliciousIpsRoute
  '/phishing-urls': typeof PhishingUrlsRoute
  '/reports': typeof ReportsRoute
  '/scam-messages': typeof ScamMessagesRoute
  '/settings': typeof SettingsRoute
  '/spam-calls': typeof SpamCallsRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call-sms-intel'
    | '/chatbot'
    | '/dashboard'
    | '/email-scams'
    | '/malicious-ips'
    | '/phishing-urls'
    | '/reports'
    | '/scam-messages'
    | '/settings'
    | '/spam-calls'
    | '/threats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/call-sms-intel'
    | '/chatbot'
    | '/dashboard'
    | '/email-scams'
    | '/malicious-ips'
    | '/phishing-urls'
    | '/reports'
    | '/scam-messages'
    | '/settings'
    | '/spam-calls'
    | '/threats'
  id:
    | '__root__'
    | '/'
    | '/call-sms-intel'
    | '/chatbot'
    | '/dashboard'
    | '/email-scams'
    | '/malicious-ips'
    | '/phishing-urls'
    | '/reports'
    | '/scam-messages'
    | '/settings'
    | '/spam-calls'
    | '/threats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallSmsIntelRoute: typeof CallSmsIntelRoute
  ChatbotRoute: typeof ChatbotRoute
  DashboardRoute: typeof DashboardRoute
  EmailScamsRoute: typeof EmailScamsRoute
  MaliciousIpsRoute: typeof MaliciousIpsRoute
  PhishingUrlsRoute: typeof PhishingUrlsRoute
  ReportsRoute: typeof ReportsRoute
  ScamMessagesRoute: typeof ScamMessagesRoute
  SettingsRoute: typeof SettingsRoute
  SpamCallsRoute: typeof SpamCallsRoute
  ThreatsRoute: typeof ThreatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threats': {
      id: '/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof ThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spam-calls': {
      id: '/spam-calls'
      path: '/spam-calls'
      fullPath: '/spam-calls'
      preLoaderRoute: typeof SpamCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scam-messages': {
      id: '/scam-messages'
      path: '/scam-messages'
      fullPath: '/scam-messages'
      preLoaderRoute: typeof ScamMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phishing-urls': {
      id: '/phishing-urls'
      path: '/phishing-urls'
      fullPath: '/phishing-urls'
      preLoaderRoute: typeof PhishingUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malicious-ips': {
      id: '/malicious-ips'
      path: '/malicious-ips'
      fullPath: '/malicious-ips'
      preLoaderRoute: typeof MaliciousIpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-scams': {
      id: '/email-scams'
      path: '/email-scams'
      fullPath: '/email-scams'
      preLoaderRoute: typeof EmailScamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-sms-intel': {
      id: '/call-sms-intel'
      path: '/call-sms-intel'
      fullPath: '/call-sms-intel'
      preLoaderRoute: typeof CallSmsIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallSmsIntelRoute: CallSmsIntelRoute,
  ChatbotRoute: ChatbotRoute,
  DashboardRoute: DashboardRoute,
  EmailScamsRoute: EmailScamsRoute,
  MaliciousIpsRoute: MaliciousIpsRoute,
  PhishingUrlsRoute: PhishingUrlsRoute,
  ReportsRoute: ReportsRoute,
  ScamMessagesRoute: ScamMessagesRoute,
  SettingsRoute: SettingsRoute,
  SpamCallsRoute: SpamCallsRoute,
  ThreatsRoute: ThreatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
