/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreatsRouteImport } from './routes/threats'
import { Route as SpamCallsRouteImport } from './routes/spam-calls'
import { Route as ScamMessagesRouteImport } from './routes/scam-messages'
import { Route as PhishingUrlsRouteImport } from './routes/phishing-urls'
import { Route as MaliciousIpsRouteImport } from './routes/malicious-ips'
import { Route as EmailScamsRouteImport } from './routes/email-scams'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1EntityRouteImport } from './routes/api/v1/$entity'
import { Route as ApiV1ScamDetectorResultsRouteImport } from './routes/api/v1/scam-detector.results'
import { Route as ApiV1DashboardMetricsRouteImport } from './routes/api/v1/dashboard.metrics'
import { Route as ApiV1EntityIdRouteImport } from './routes/api/v1/$entity.$id'

const ThreatsRoute = ThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const SpamCallsRoute = SpamCallsRouteImport.update({
  id: '/spam-calls',
  path: '/spam-calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamMessagesRoute = ScamMessagesRouteImport.update({
  id: '/scam-messages',
  path: '/scam-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PhishingUrlsRoute = PhishingUrlsRouteImport.update({
  id: '/phishing-urls',
  path: '/phishing-urls',
  getParentRoute: () => rootRouteImport,
} as any)
const MaliciousIpsRoute = MaliciousIpsRouteImport.update({
  id: '/malicious-ips',
  path: '/malicious-ips',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailScamsRoute = EmailScamsRouteImport.update({
  id: '/email-scams',
  path: '/email-scams',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EntityRoute = ApiV1EntityRouteImport.update({
  id: '/api/v1/$entity',
  path: '/api/v1/$entity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ScamDetectorResultsRoute =
  ApiV1ScamDetectorResultsRouteImport.update({
    id: '/api/v1/scam-detector/results',
    path: '/api/v1/scam-detector/results',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1DashboardMetricsRoute = ApiV1DashboardMetricsRouteImport.update({
  id: '/api/v1/dashboard/metrics',
  path: '/api/v1/dashboard/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EntityIdRoute = ApiV1EntityIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1EntityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/dashboard': typeof DashboardRoute
  '/email-scams': typeof EmailScamsRoute
  '/malicious-ips': typeof MaliciousIpsRoute
  '/phishing-urls': typeof PhishingUrlsRoute
  '/scam-messages': typeof ScamMessagesRoute
  '/spam-calls': typeof SpamCallsRoute
  '/threats': typeof ThreatsRoute
  '/api/v1/$entity': typeof ApiV1EntityRouteWithChildren
  '/api/v1/$entity/$id': typeof ApiV1EntityIdRoute
  '/api/v1/dashboard/metrics': typeof ApiV1DashboardMetricsRoute
  '/api/v1/scam-detector/results': typeof ApiV1ScamDetectorResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/dashboard': typeof DashboardRoute
  '/email-scams': typeof EmailScamsRoute
  '/malicious-ips': typeof MaliciousIpsRoute
  '/phishing-urls': typeof PhishingUrlsRoute
  '/scam-messages': typeof ScamMessagesRoute
  '/spam-calls': typeof SpamCallsRoute
  '/threats': typeof ThreatsRoute
  '/api/v1/$entity': typeof ApiV1EntityRouteWithChildren
  '/api/v1/$entity/$id': typeof ApiV1EntityIdRoute
  '/api/v1/dashboard/metrics': typeof ApiV1DashboardMetricsRoute
  '/api/v1/scam-detector/results': typeof ApiV1ScamDetectorResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/dashboard': typeof DashboardRoute
  '/email-scams': typeof EmailScamsRoute
  '/malicious-ips': typeof MaliciousIpsRoute
  '/phishing-urls': typeof PhishingUrlsRoute
  '/scam-messages': typeof ScamMessagesRoute
  '/spam-calls': typeof SpamCallsRoute
  '/threats': typeof ThreatsRoute
  '/api/v1/$entity': typeof ApiV1EntityRouteWithChildren
  '/api/v1/$entity/$id': typeof ApiV1EntityIdRoute
  '/api/v1/dashboard/metrics': typeof ApiV1DashboardMetricsRoute
  '/api/v1/scam-detector/results': typeof ApiV1ScamDetectorResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chatbot'
    | '/dashboard'
    | '/email-scams'
    | '/malicious-ips'
    | '/phishing-urls'
    | '/scam-messages'
    | '/spam-calls'
    | '/threats'
    | '/api/v1/$entity'
    | '/api/v1/$entity/$id'
    | '/api/v1/dashboard/metrics'
    | '/api/v1/scam-detector/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chatbot'
    | '/dashboard'
    | '/email-scams'
    | '/malicious-ips'
    | '/phishing-urls'
    | '/scam-messages'
    | '/spam-calls'
    | '/threats'
    | '/api/v1/$entity'
    | '/api/v1/$entity/$id'
    | '/api/v1/dashboard/metrics'
    | '/api/v1/scam-detector/results'
  id:
    | '__root__'
    | '/'
    | '/chatbot'
    | '/dashboard'
    | '/email-scams'
    | '/malicious-ips'
    | '/phishing-urls'
    | '/scam-messages'
    | '/spam-calls'
    | '/threats'
    | '/api/v1/$entity'
    | '/api/v1/$entity/$id'
    | '/api/v1/dashboard/metrics'
    | '/api/v1/scam-detector/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatbotRoute: typeof ChatbotRoute
  DashboardRoute: typeof DashboardRoute
  EmailScamsRoute: typeof EmailScamsRoute
  MaliciousIpsRoute: typeof MaliciousIpsRoute
  PhishingUrlsRoute: typeof PhishingUrlsRoute
  ScamMessagesRoute: typeof ScamMessagesRoute
  SpamCallsRoute: typeof SpamCallsRoute
  ThreatsRoute: typeof ThreatsRoute
  ApiV1EntityRoute: typeof ApiV1EntityRouteWithChildren
  ApiV1DashboardMetricsRoute: typeof ApiV1DashboardMetricsRoute
  ApiV1ScamDetectorResultsRoute: typeof ApiV1ScamDetectorResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threats': {
      id: '/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof ThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spam-calls': {
      id: '/spam-calls'
      path: '/spam-calls'
      fullPath: '/spam-calls'
      preLoaderRoute: typeof SpamCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scam-messages': {
      id: '/scam-messages'
      path: '/scam-messages'
      fullPath: '/scam-messages'
      preLoaderRoute: typeof ScamMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phishing-urls': {
      id: '/phishing-urls'
      path: '/phishing-urls'
      fullPath: '/phishing-urls'
      preLoaderRoute: typeof PhishingUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malicious-ips': {
      id: '/malicious-ips'
      path: '/malicious-ips'
      fullPath: '/malicious-ips'
      preLoaderRoute: typeof MaliciousIpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-scams': {
      id: '/email-scams'
      path: '/email-scams'
      fullPath: '/email-scams'
      preLoaderRoute: typeof EmailScamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$entity': {
      id: '/api/v1/$entity'
      path: '/api/v1/$entity'
      fullPath: '/api/v1/$entity'
      preLoaderRoute: typeof ApiV1EntityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/scam-detector/results': {
      id: '/api/v1/scam-detector/results'
      path: '/api/v1/scam-detector/results'
      fullPath: '/api/v1/scam-detector/results'
      preLoaderRoute: typeof ApiV1ScamDetectorResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/dashboard/metrics': {
      id: '/api/v1/dashboard/metrics'
      path: '/api/v1/dashboard/metrics'
      fullPath: '/api/v1/dashboard/metrics'
      preLoaderRoute: typeof ApiV1DashboardMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$entity/$id': {
      id: '/api/v1/$entity/$id'
      path: '/$id'
      fullPath: '/api/v1/$entity/$id'
      preLoaderRoute: typeof ApiV1EntityIdRouteImport
      parentRoute: typeof ApiV1EntityRoute
    }
  }
}

interface ApiV1EntityRouteChildren {
  ApiV1EntityIdRoute: typeof ApiV1EntityIdRoute
}

const ApiV1EntityRouteChildren: ApiV1EntityRouteChildren = {
  ApiV1EntityIdRoute: ApiV1EntityIdRoute,
}

const ApiV1EntityRouteWithChildren = ApiV1EntityRoute._addFileChildren(
  ApiV1EntityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatbotRoute: ChatbotRoute,
  DashboardRoute: DashboardRoute,
  EmailScamsRoute: EmailScamsRoute,
  MaliciousIpsRoute: MaliciousIpsRoute,
  PhishingUrlsRoute: PhishingUrlsRoute,
  ScamMessagesRoute: ScamMessagesRoute,
  SpamCallsRoute: SpamCallsRoute,
  ThreatsRoute: ThreatsRoute,
  ApiV1EntityRoute: ApiV1EntityRouteWithChildren,
  ApiV1DashboardMetricsRoute: ApiV1DashboardMetricsRoute,
  ApiV1ScamDetectorResultsRoute: ApiV1ScamDetectorResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
